matrix:
- name: Markdown
  aspell:
    lang: en
    # Only use lower case words in .wordlist.txt
    ignore-case: true
  dictionary:
    wordlists:
      - .wordlist.txt
    encoding: utf-8
  pipeline:
  - pyspelling.filters.markdown:
  - pyspelling.filters.html:
      comments: false
      ignores:
        - code
        - pre
  sources:
    - '**/*.md'
  default_encoding: utf-8