site_name: Libre Train Sim documentation
theme:
  name: readthedocs #'rtd-dropdown'

plugins:
  - search

# Cheatsheet: https://stephane-cheatsheets.readthedocs.io/en/latest/misc/readthedocs_mkdocs/

markdown_extensions:
  - toc:
      permalink: true
  - abbr
  - admonition
  - codehilite
#  - pymdownx.arithmatex
#  - pymdownx.betterem:
#      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.snippets
  - pymdownx.tasklist:
      custom_checkbox: false
  - pymdownx.tabbed
  - pymdownx.tilde
  #- pymdownx.emoji:
  #   emoji_index: !!python/name:materialx.emoji.twemoji
  #   emoji_generator: !!python/name:materialx.emoji.to_svg
