# Project information
site_name: Libre TrainSim documentation
site_description: Documentation for Libre TrainSim
site_author: Libre TrainSim documentation contributers
site_url: https://libretrainsim.org/

# Repository information
repo_name: lts-docs
repo_url: https://github.com/Libre-TrainSim/lts-docs/

theme:
  name: readthedocs
  collapse_navigation: false


plugins:
  - search
  - awesome-pages:
      collapse_single_pages: true

# We need some special navigation overrides to clean the sidebar up a little bit.
# Refer to https://github.com/lukasgeiter/mkdocs-awesome-pages-plugin for an overview of the available features.

nav:
  - Home: index.md
  - ...


# Cheatsheet: https://stephane-cheatsheets.readthedocs.io/en/latest/misc/readthedocs_mkdocs/

markdown_extensions:
  - toc:
      permalink: true
  - abbr
  - admonition
  - codehilite
#  - pymdownx.arithmatex
#  - pymdownx.betterem:
#      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.snippets
  - pymdownx.tasklist:
      custom_checkbox: false
  - pymdownx.tabbed
  - pymdownx.tilde
  #- pymdownx.emoji:
  #   emoji_index: !!python/name:materialx.emoji.twemoji
  #   emoji_generator: !!python/name:materialx.emoji.to_svg
