name: Spellcheck
on: 
  push: 
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    # https://github.com/marketplace/actions/github-spellcheck-action
    - uses: rojopolis/spellcheck-github-actions@0.21.1
      name: Spellcheck
      with:
        config_path: .spellcheck.yml